Repository terragraph/meta-terragraph, pull requests merged in 2022-08, with the labels that each got.

#21 fix(puff): fix 'kvstore prefixes --json' command
  src/terragraph-e2e/lua/puff.lua
Labels: bug, CLA Signed

#23 Add tests step to build-terragraph-image-x86 GitHub Actions Workflow
  .github/workflows/build-terragraph-image-x86.yml
Labels: enhancement, CLA Signed

#27 feat(openr): Update Open/R source reference
  recipes-support/openr/files/fix-platform-linux-handler.patch
  recipes-support/openr/openr_src.inc
  utils/sync_yocto_utils.sh
Labels: CLA Signed

#25 Automatically publish e2e-controller container to the GitHub Container Repository
  .github/workflows/build-terragraph-image-x86.yml
Labels: enhancement, CLA Signed

#28 feat(ci): Add sync-source-mirrors job after successful x86 build
  .github/workflows/terragraph-image-x86.yml
  conf/generate-tarballs.conf
Labels: enhancement, CLA Signed

#30 docs: add links to terragraph-planner
  docusaurus/docusaurus.config.js
  docusaurus/src/pages/index.js
Labels: documentation, CLA Signed

#31 feat(ci): run check-bitbake-recipe-updates.py weekly
  .github/workflows/check-bitbake-recipe-updates.yml
  utils/check-bitbake-recipe-updates.py
Labels: enhancement, CLA Signed

#33 feat(ci): run flake8 in python_ci
  .flake8
  .github/workflows/python_ci.yml
  docs/developer/Service_Scripts.md
  recipes-facebook/tg-utils/files/pop_unreachable_cmd.py
  recipes-radio/tg-scripts/files/scripts/cpu_mem_profile.py
  src/tg/tg/commands/config.py
  src/tg/tg/commands/fw.py
  src/update_firewall/update_firewall.py
  utils/scan_verif_p3.py
Labels: enhancement, CLA Signed
