Repository terragraph/meta-terragraph, pull requests merged in 2022-07, with the labels that each got.

#3 Fix utils/README.md formatting
  utils/README.md
Labels: CLA Signed

#4 feat(docusaurus): website tweaks
  docusaurus/docusaurus.config.js
  docusaurus/src/pages/index.js
Labels: documentation, CLA Signed

#5 feat(docusaurus): add algolia search bar
  docusaurus/docusaurus.config.js
Labels: documentation, enhancement, CLA Signed

#6 feat(docusaurus): update to 2.0.0-beta.21
  .github/workflows/deploy-gh-pages.yml
  docusaurus/README.md
  docusaurus/docusaurus.config.js
  docusaurus/package.json
  docusaurus/src/pages/index.js
  docusaurus/yarn.lock
Labels: documentation, CLA Signed

#7 misc: improve Meta-internal build setup
  .gitignore
  README.md
  conf/layer.conf
  facebook/conf/allow-all-networks.conf
  facebook/conf/release.conf
  facebook/conf/site.conf
  facebook/workaround-bin/git
  tg-init-build-env
  utils/make_builds.sh
  utils/sync_yocto_utils.sh
Labels: enhancement, CLA Signed

#1 fixed multipath support, added TCP MD5 signature config generation
  recipes-facebook/e2e/e2e-files_0.1.bb
  recipes-support/frrouting/frrouting/sv/bgpd.run
  src/terragraph-e2e/e2e/config/bgpd.conf.template
  src/terragraph-e2e/e2e/config/config_metadata.json
  src/terragraph-e2e/lua/tg/frr_utils.lua
Labels: enhancement, CLA Signed

#8 fix(tg95): add missing build directory
  src/tg95/build/asset-manifest.json
  src/tg95/build/index.html
  src/tg95/build/precache-manifest.8d3258ee41115abcf23d89b4dbe9fada.js
  src/tg95/build/service-worker.js
  src/tg95/build/static/js/2.4404512c.chunk.js
  src/tg95/build/static/js/3.49f752ca.chunk.js
  src/tg95/build/static/js/4.fa1fb945.chunk.js
  src/tg95/build/static/js/main.bf21edd6.chunk.js
  src/tg95/build/static/js/runtime-main.b1dfee7a.js
  src/tg95/build/static/media/ms_sans_serif.1d4d404a.woff2
  src/tg95/build/static/media/ms_sans_serif_bold.cb1c7473.woff2
  src/tg95/build/styles.css
Labels: bug, CLA Signed

#9 fix(docusaurus): regenerate yarn.lock
  docusaurus/yarn.lock
Labels: bug, documentation, CLA Signed

#10 fix(docusaurus): fix index page modal content css
  docusaurus/src/pages/index.js
Labels: bug, documentation, CLA Signed

#2 fix(meta-terragraph): Remove Meta-specific dotfiles
  .jfconfig
Labels: bug, CLA Signed

#12 kill of stuck vpp_chaperone instance upon vpp restart
  meta-qoriq/recipes-facebook/tg-vpp/files/etc/sv/vpp/vpp.run
Labels: bug, CLA Signed

#15 Add ptr CI run
  .github/workflows/python_ci.yml
  .ptrconfig
  src/exabgp_to_openr/setup.py
  src/exaconf/exaconf/tests/base.py
  src/exaconf/setup.py
  src/r2d2/r2d2/help.py
  src/r2d2/r2d2/r2d2.py
  src/r2d2/r2d2/tests/r2d2_commands_test.py
  src/r2d2/setup.py
  src/tg/setup.py
  src/tg/tg/commands/config.py
  src/tg/tg/commands/counters.py
  src/tg/tg/commands/debug.py
  src/tg/tg/commands/event.py
  src/tg/tg/commands/fw.py
  src/tg/tg/commands/help.py
  src/tg/tg/commands/ignition.py
  src/tg/tg/commands/link.py
  src/tg/tg/commands/minion.py
  src/tg/tg/commands/node.py
  src/tg/tg/commands/scan.py
  src/tg/tg/commands/site.py
  src/tg/tg/commands/status.py
  src/tg/tg/commands/topology.py
  src/tg/tg/commands/upgrade/upgrade.py
  src/tg/tg/commands/upgrade/upgrade_base.py
  src/tg/tg/commands/upgrade/upgrade_state.py
  src/tg/tg/commands/upgrade/upgrade_torrent.py
  src/tg/tg/commands/version.py
  src/tg/tg/commands/zeroize.py
  src/tg/tg/tests/base.py
  src/tg/tg/tests/test_consts.py
  src/tg/tg/tests/test_scan_fixtures.py
  src/tg/tg/tg.py
  src/update_firewall/setup.py
  src/update_firewall/update_firewall.py
  src/vpp_plugins/python_utils/vpp_utils.py
Labels: CLA Signed

#17 fix(lua): fix tg_frr_utils_test.lua
  src/terragraph-e2e/lua/tests/tg_frr_utils_test.lua
Labels: bug, CLA Signed

#18 feat(lua): add lua_ci.yml workflow
  .github/workflows/lua_ci.yml
Labels: enhancement, CLA Signed

#14 Add build-terragraph-image-x86 GitHub Actions Workflow
  .github/workflows/build-terragraph-image-x86.yml
Labels: enhancement, CLA Signed

#19 fix(openr): fix platform_linux crashing on startup
  recipes-facebook/openr/files/sv/fib_linux.run
  recipes-support/openr/files/fix-platform-linux-handler.patch
  recipes-support/openr/openr_src.inc
Labels: bug, CLA Signed

#20 fix: skip build job on forks
  .github/workflows/build-terragraph-image-x86.yml
Labels: bug, CLA Signed
